# Generated by Django 5.0.7 on 2025-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PlaceholderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='domain name', blank=True)),
                ('name', models.CharField(max_length=50, verbose_name='display name', blank=True)),
            ],
        ),
    ]
