# Generated by Django 5.1.7 on 2025-03-15 14:56

import django.db.models.deletion
from django.apps import apps
from django.db import migrations, models

config = apps.get_app_config("sitevars")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(config.sites_model),
        ('sitevars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('value', models.TextField(verbose_name='value')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vars', to=config.sites_model, verbose_name='site')),
            ],
            options={
                'verbose_name': 'site variable',
                'verbose_name_plural': 'site variables',
                'base_manager_name': 'objects',
                'unique_together': {('site', 'name')},
            },
        ),
    ]
